### PR TITLE
Amanuel ghebreamlak ghebremedhin

### PR DESCRIPTION
**Pull request by amanuelghe84**

### CODE REVIEW

**Comment by adamacadamy** [comment]
you have removed previous code challenges and the folder structure is wrong

**Comment by adamacadamy** [comment]
you have solved the code challenge but please remove the comments

**Comment by amanuelghe84** [comment]
@adamacadamy I will resolve

**Comment by amanuelghe84** [comment]
resolvier

**Comment by fuzumoe** [comment]
good job done!

**Pull request merged**
